### ISSUE TITLE
Publicar a versão v1.0

### ISSUE THREAD

**Issue by boidacarapreta** [ederson-torresini/adcipt20232#55]
O jogo deve preencher os seguintes requisitos:

- [x] Suporte a toque de tela #25;
- [x] Tela cheia #30;
- [x] Salas de partida #36;
- [x] Multijogador #37;
- [x] Publicação de conteúdo estático #45;
- [x] Publicação de conteúdo dinâmico #46.
- [x] Áudio sobre WebRTC #50;
- [x] Validação em teste alfa #51.
- [x] PWA #54.

Assim, deve ser marcado o _commit_ com a versão estável e publicá-la na nuvem.

**Comment by ederson-torresini** [comment]
Versão `v1.0` publicada.
